version: "{build}"

os: Windows Server 2012
platform:
  - x64

environment:
  matrix:
    - ruby_version: "21"

clone_folder: c:\projects\chefdk
clone_depth: 1
skip_tags: true
branches:
  only:
    - master

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - C:\Ruby%ruby_version%\DevKit\devkitvars.bat
  - echo %PATH%
  - ruby C:\Ruby%ruby_version%\DevKit\dk.rb init
  - ruby C:\Ruby%ruby_version%\DevKit\dk.rb install
  - ruby --version
  - gem --version
  - gem install bundler --quiet --no-ri --no-rdoc
  - bundler --version

build_script:
  - bundle install --path bundle/vendor

test_script:
  - bundle exec rspec --path bundle/vendor

cache:
  - c:\projects\chefdk\bundle
