version: "{build}"

os: Windows Server 2012
platform:
  - x64

environment:
  matrix:
    - ruby_version: "200"

clone_folder: c:\projects\chefdk
clone_depth: 1
skip_tags: true
branches:
  only:
    - master

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - ruby --version
  - gem --version
  - gem install bundler --quiet --no-ri --no-rdoc
  - bundler --version
  - appveyor DownloadFile https://github.com/jdmundrawala/dep-selector-libgecode/releases/download/v1.0.2/dep-selector-libgecode-1.0.2-x86-mingw32.gem -O dep-selector-libgecode-1.0.2-x86-mingw32.gem
  - gem install dep-selector-libgecode-1.0.2-x86-mingw32.gem

build_script:
  - bundle install

test_script:
  - bundle exec rspec
