version: "{build}"

os: Windows Server 2012
platform:
  - x64

environment:
  matrix:
    - ruby_version: "200"

clone_folder: c:\projects\chefdk
clone_depth: 1
skip_tags: true
branches:
  only:
    - master

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ls c:\Ruby%ruby_version%\DevKit\mingw\bin
  - cp C:\Ruby%ruby_version%\DevKit\mingw\bin\bsdtar.exe C:\Ruby%ruby_version%\bin\tar.exe
  - ls c:\Ruby%ruby_version%\bin
  - C:\Ruby%ruby_version%\DevKit\mingw\bin\bsdtar.exe --version
  - tar.exe --version
  - ruby --version
  - gem --version
  - gem install bundler --quiet --no-ri --no-rdoc
  - bundler --version

build_script:
  - bundle install --path bundle/vendor

test_script:
  - bundle exec rspec --path bundle/vendor

cache:
  - bundle
